version: '3'
services: 
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment: 
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - ./devicedata/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null 

  platform:
    build: .
    container_name: platform
    ports:
      - 5000:5000
    environment: 
      - MQTT_HOST=mqtt
      - MONGODB_FOR_DEVICE_DATA=True
      - DATASTORAGE_URI=mongodb://mongodb:27017
    depends_on: 
      - mqtt
      - mongodb
    volumes:
      - .:/app
